test.myName: 111

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/scstore
    username: root
    password: root

server.port: 0

---
spring:
  zipkin:
    base-url: http://zipkin-server:9411


